apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
#kubernetes resources to be managed by kustomize
resources:
  - monitoring-config.yml
  - monitoring-kustomization-prometheus-stack.yml
  - monitoring-source-prometheus-stack.yml