apiVersion: apps/v1
kind: Deployment
metadata:
  name: portainer
  namespace: portainer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portainer
  template:
    metadata:
      labels:
        app: portainer
    spec:
      containers:
        - name: portainer
          image: portainer/portainer-ce:latest
          ports:
            - containerPort: 9000
          args:
            - "--admin-password"
            - ":$2y$05$APd5vsQhxjXZeKUnqGH0BO8F3ajj1q47SOOAE4HE98coQnIDF7llq"  # Replace with a secure password