apiVersion: v1
kind: Service
metadata:
  name: portainer
  namespace: portainer
spec:
  ports:
    - port: 9000
      targetPort: 9000
  selector:
    app: portainer
  type: NodePort # or NodePort, depending on your setup